# We only use isolated builds for PR validation

trigger: none # so no CI triggers

pool:
  vmImage: ubuntu-latest

steps:
  - template: templates/build-js.steps.yml
    parameters:
      packageName: client-app
