# We only use isolated builds for PR validation

trigger: none # so no CI triggers

pool:
  vmImage: ubuntu-latest

steps:
  - template: templates/build-next-standalone.steps.yml
    parameters:
      packageName: frontend-webapp
      packageRoot: app/frontend-webapp
      includeStaticAssets: true
      nodeVersion: 18.12.x
