# We only use isolated builds for PR validation

trigger: none # so no CI triggers

pool:
  vmImage: ubuntu-latest

variables:
  project: ./app/Monitor/Monitor.csproj
  build-config: release

steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 8.x
    displayName: Setup .NET

  - bash: >-
      dotnet build
      $(project)
      -c $(build-config)
    displayName: dotnet build
