trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  # deploy
  azureSubscription: Research Unmanaged NUH (R02287-1)
  uatEnv: NUH RedCap Monitor UAT
  prodEnv: NUH RedCap Monitor Prod

stages:
  - stage: Publish_WebFrontend
    jobs:
      - job: Publish_FrontendWebApp
        variables:
          packageRoot: app/frontend-webapp
        displayName: Publish Frontend Web App
        steps:
          # Build the app
          - template: templates/build-next-standalone.steps.yml
            parameters:
              packageName: $(frontendPackageName)
              packageRoot: $(packageRoot)
              includeStaticAssets: true
              nodeVersion: 18.12.x
          # publish artifact
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(packageRoot)/.next/standalone
              artifact: $(frontendPackageName)

  - stage: Deploy_Uat
    displayName: Deploy UAT
    dependsOn: Publish_WebFrontend
    jobs:
      - template: templates/deploy-app-service.jobs.yml
        parameters:
          jobName: DeployFrontendWebApp
          displayName: Deploy Frontend Web App
          environment: $(uatEnv)
          artifact: $(frontendPackageName)
          azureSubscription: $(azureSubscription)
          appName: uat-monitor-frontend

  - stage: Deploy_Prod
    displayName: Deploy Prod
    dependsOn: Publish_WebFrontend
    jobs:
      - template: templates/deploy-app-service.jobs.yml
        parameters:
          jobName: DeployFrontendWebApp
          displayName: Deploy Frontend Web App
          environment: $(prodEnv)
          artifact: $(frontendPackageName)
          azureSubscription: $(azureSubscription)
          appName: prod-monitor-frontend
