trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  # build / publish
  function-project: ./app/Functions/Functions.csproj
  dotnet-buildConfig: release

  # deploy
  azureSubscription: Research Unmanaged NUH (R02287-1)
  uatEnv: NUH RedCap Monitor UAT
  prodEnv: NUH RedCap Monitor Prod

stages:
  - stage: Publish
    jobs:
      - job:
        displayName: Publish function app
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: 7.x
            displayName: Setup .NET

          - bash: >-
              dotnet publish
              $(function-project)
              -c $(dotnet-buildConfig)
              -o $(Build.StagingDirectory)
            displayName: dotnet publish

          - publish: $(Build.StagingDirectory)
            artifact: function
            displayName: Publish function artifact

  - stage: Deploy_Uat
    displayName: Deploy UAT
    dependsOn: Publish
    jobs:
      - template: templates/deploy-functions-app.jobs.yml
        parameters:
          jobName: DeployFunctionsApp
          displayName: Deploy Functions App
          environment: $(uatEnv)
          artifact: function
          azureServiceConnection: $(azureSubscription)
          appName: uat-monitor-worker

  - stage: Deploy_Prod
    displayName: Deploy Prod
    dependsOn: Publish
    jobs:
      - template: templates/deploy-functions-app.jobs.yml
        parameters:
          jobName: DeployFunctionsApp
          displayName: Deploy Functions App
          environment: $(prodEnv)
          artifact: function
          azureServiceConnection: $(azureSubscription)
          appName: prod-monitor-worker
