trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  # build / publish
  data-project: ./app/Data/Data.csproj
  webapp-project: ./app/Monitor/Monitor.csproj
  dotnet-buildConfig: release

  # deploy
  azureSubscription: Research Unmanaged NUH (R02287-1)
  azureResourceGroup: rg-prj-rum-we-R02287-1
  dbServer: monitor-uat # default to uat
  uatEnv: NUH RedCap Monitor UAT
  prodEnv: NUH RedCap Monitor Prod

stages:
  - stage: Publish
    jobs:
      - template: templates/publish-migrations-bundle.jobs.yml
        parameters:
          migrationsProject: $(data-project)
          project: $(webapp-project)
          buildConfig: $(dotnet-buildConfig)

      - job: Publish_WebApp
        displayName: Publish Web App
        steps:
          # Get short Git Commit Hash
          - bash: |
              echo "##vso[task.setvariable variable=GitHash]$(git describe --always)"
            displayName: Get git commit hash

          # Publish the .NET App
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: 7.x
            displayName: Setup .NET

          - bash: >-
              dotnet publish
              $(webapp-project)
              -c $(dotnet-buildConfig)
              -o $(Build.StagingDirectory)
              -p:GitHash=$(GitHash)
            displayName: dotnet publish

          - publish: $(Build.StagingDirectory)
            artifact: webapp
            displayName: Publish webapp artifact

  - stage: Deploy_Uat
    displayName: Deploy UAT
    dependsOn: Publish
    jobs:
      # Db Migrations should depend on ALL app deployment jobs
      # if those jobs are part of templates,
      # get the job names from the templates or their parameters :)
      - template: templates/deploy-migrations-bundle.jobs.yml
        parameters:
          dependsOn:
            - DeployWebApp
          environment: $(uatEnv)
          azureSubscription: $(azureSubscription)
          resourceGroup: $(azureResourceGroup)
          dbServerName: $(dbServer)
          keyVaultName: monitor-uat

      - template: templates/deploy-app-service.jobs.yml
        parameters:
          jobName: DeployWebApp
          displayName: Deploy Web App
          environment: $(uatEnv)
          artifact: webapp
          azureSubscription: $(azureSubscription)
          appName: uat-monitor

  - stage: Deploy_Prod
    displayName: Deploy Prod
    dependsOn: Publish
    variables:
      dbServer: monitor-prod
    jobs:
      # Db Migrations should depend on ALL app deployment jobs
      # if those jobs are part of templates,
      # get the job names from the templates or their parameters :)
      - template: templates/deploy-migrations-bundle.jobs.yml
        parameters:
          dependsOn:
            - DeployWebApp
          environment: $(prodEnv)
          azureSubscription: $(azureSubscription)
          resourceGroup: $(azureResourceGroup)
          dbServerName: $(dbServer)
          keyVaultName: monitor-prod

      - template: templates/deploy-app-service.jobs.yml
        parameters:
          jobName: DeployWebApp
          displayName: Deploy Web App
          environment: $(prodEnv)
          artifact: webapp
          azureSubscription: $(azureSubscription)
          appName: prod-monitor
