trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  # deploy
  azureSubscription: Research Unmanaged NUH (R02287-1)
  uatEnv: NUH RedCap Monitor UAT
  prodEnv: NUH RedCap Monitor Prod

stages:
  - stage: Publish_Web
    jobs:
      - job: Publish_WebApp
        displayName: Publish Web App
        steps:
          # Build the client-app
          - template: templates/build-js.steps.yml
            parameters:
              packageName: client-app

  - stage: Deploy_Uat
    displayName: Deploy UAT
    dependsOn: Publish_Web
    jobs:
      - template: templates/deploy-app-service.jobs.yml
        parameters:
          jobName: DeployWebApp
          displayName: Deploy Web App
          environment: $(uatEnv)
          artifact: drop
          azureSubscription: $(azureSubscription)
          appName: uat-monitor-frontend

  - stage: Deploy_Prod
    displayName: Deploy Prod
    dependsOn: Publish_Web
    jobs:
      - template: templates/deploy-app-service.jobs.yml
        parameters:
          jobName: DeployWebApp
          displayName: Deploy Web App
          environment: $(prodEnv)
          artifact: drop
          azureSubscription: $(azureSubscription)
          appName: prod-monitor-frontend
