env:
  browser: true
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended"
  - next/core-web-vitals
  - plugin:@next/next/recommended
plugins:
  - prettier
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  react/react-in-jsx-scope: 0
  react/jsx-uses-react: 0
  react/prop-types: 0
  eslint/no-unused-vars: 0
  prettier/prettier:
    - error
    - endOfLine: auto
