env:
  browser: true
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@next/next/recommended
plugins:
  - prettier
  - '@typescript-eslint'
  - 'simple-import-sort'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  react/react-in-jsx-scope: 0
  react/jsx-uses-react: 0
  react/prop-types: 0
  eslint/no-unused-vars: 0
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
  prettier/prettier:
    - warn
    - endOfLine: auto
  '@typescript-eslint/no-unused-vars': warn
settings:
  next:
    rootDir: app/frontend-webapp/
