name: nuh-local-dev

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

  azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"

  keycloakdb:
      image: postgres:15
      restart: always
      ports:
        - 5433:5432
      volumes:
        - keycloak_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: keycloak_user
        POSTGRES_PASSWORD: keycloak_password
        POSTGRES_DB: keycloak

  keycloak:
      image: docker.io/bitnami/keycloak:latest
      restart: always
      ports:
        - 9080:8080
      environment:
        KEYCLOAK_ADMIN_USER: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KEYCLOAK_DATABASE_PORT: 5433
        KEYCLOAK_DATABASE_HOST: host.docker.internal
        KEYCLOAK_DATABASE_NAME: keycloak
        KEYCLOAK_DATABASE_USER: keycloak_user
        KEYCLOAK_DATABASE_PASSWORD: keycloak_password
      depends_on:
        - keycloakdb

volumes:
  keycloak_data:
    driver: local
