name: nuh-local-dev

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

  azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
