# TODO: Convert this into a .bicepparam file once they support imports

# Site Customisation
OutboundEmail__FromAddress: "noreply@example.com"
OutboundEmail__FromName: "RedCap Monitor"

# Sythetic Data Rules
SyntheticDataMapping:
  Mappings:
    - FieldName: weight
      MeasurementUnit: ""
      MinValue: "50"
      MaxValue: "120"
    - FieldName: weight
      MeasurementUnit: Kg
      MinValue: "50"
      MaxValue: "120"
    - FieldName: weight
      MeasurementUnit: lbs
      MinValue: "130"
      MaxValue: "300"
    - FieldName: weight
      MeasurementUnit: stones
      MinValue: "4"
      MaxValue: "20"
    - FieldName: height
      MeasurementUnit: cm
      MinValue: "150"
      MaxValue: "200"
    - FieldName: height
      MeasurementUnit: Metres
      MinValue: "1"
      MaxValue: "2"
    - FieldName: height
      MeasurementUnit: m
      MinValue: "1"
      MaxValue: "2"
    - FieldName: height
      MeasurementUnit: feet
      MinValue: "3"
      MaxValue: "8"
    - FieldName: age
      MeasurementUnit: ""
      MinValue: "18"
      MaxValue: "65"
    - FieldName: age
      MeasurementUnit: years
      MinValue: "18"
      MaxValue: "65"
    - FieldName: dob
      MeasurementUnit: ""
      MinValue: "01/01/1958"
      MaxValue: "31/12/2004"
