parameters:
  - name: environment
    type: string
  - name: azureServiceConnection
    type: string
  - name: artifact
    type: string
  - name: appName
    type: string
  - name: relativePackagePath
    type: string
    default: ""
  - name: isLinux
    type: boolean
    default: true
  - name: displayName
    type: string
    default: Deploy Function App
  - name: jobName
    type: string
    default: DeployFunctionApp

jobs:
  - deployment: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    environment: ${{ parameters.environment }}

    variables:
      ${{ if parameters.isLinux }}:
        appType: functionAppLinux
        vmImage: ubuntu-latest
      ${{ if not(parameters.isLinux) }}:
        appType: functionApp
        vmImage: windows-latest
    pool:
      vmImage: ${{ variables.vmImage }}

    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: ${{ parameters.artifact }}
            - task: AzureFunctionApp@2
              displayName: Deploy Azure Function App
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                appType: ${{ variables.appType }}
                appName: ${{ parameters.appName }}
                package: $(Pipeline.Workspace)/${{ parameters.artifact }}/${{ parameters.relativePackagePath }}
