parameters:
  - name: environment
    type: string
  - name: azureSubscription
    type: string
  - name: artifact
    type: string
  - name: appName
    type: string
  - name: displayName
    type: string
    default: Deploy App Service
  - name: jobName
    type: string
    default: DeployAppService

jobs:
  - deployment: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: ${{ parameters.artifact }}
            - task: AzureRmWebAppDeployment@4
              displayName: Deploy Azure AppService
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: webAppLinux
                WebAppName: ${{ parameters.appName }}
                packageForLinux: $(Pipeline.Workspace)/${{ parameters.artifact }}/
