parameters:
  - name: migrationsProject
    type: string
  - name: project
    type: string
  - name: buildConfig
    type: string
    default: release

jobs:
  - job: Publish_DbMigrations
    displayName: Publish Database Migrations Bundle
    steps:
      # validate params
      - bash: |
          if [ -z "$PROJECT" ]; then
            echo "##vso[task.logissue type=error;]Missing template parameter \"project\""
            echo "##vso[task.complete result=Failed;]"
          fi
        env:
          PROJECT: ${{ parameters.project }}
        displayName: Check for required parameters

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: 7.x
        displayName: Setup .NET

      # use the repo's copy of `dotnet ef`
      - bash: dotnet tool restore
        displayName: Restore repo dotnet tools

      # Build the migrations bundle
      - bash: >-
          dotnet ef migrations bundle
          -p ${{ parameters.project }}
          -o $(Build.StagingDirectory)/efbundle
          -r linux-x64
          --self-contained
          --configuration ${{ parameters.buildConfig }}
        displayName: Build bundle

      - publish: $(Build.StagingDirectory)
        artifact: migrations
        displayName: Publish bundle artifact
