name: Build Frontend Web App

on:
  workflow_dispatch:
  pull_request:
    paths:
      - app/frontend-webapp/**
      - .github/workflows/build.frontend-webapp.yml

env:
  PACKAGE_ROOT: app/frontend-webapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i --workspaces=false
        working-directory: ${{ env.PACKAGE_ROOT }}
        
      - name: Cache .next/cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.PACKAGE_ROOT }}/.next/cache
          key: nextjs | $(Agent.OS) | ${{ env.PACKAGE_ROOT }}/package-lock.json

      - name: Build
        run: npm run build --workspaces=false
        working-directory: ${{ env.PACKAGE_ROOT }}

      - name: Copy Static Assets
        run: |
          cp -r .next/static .next/standalone/.next/
          cp -r public .next/standalone/
        working-directory: ${{ env.PACKAGE_ROOT }} 
