name: Build Frontend, Backend and Functions App

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/build.yml

env:
  PACKAGE_ROOT: app/frontend-webapp
  DOTNET_VERSION: 8.x
  CI_backend_project: ./app/Monitor/Monitor.csproj
  WEBAPP_FUNCTIONS_PACKAGE_PATH: "./app/Functions"

jobs:
  build_WebFrontend:
    name: Build Frontend Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i --workspaces=false
        working-directory: ${{ env.PACKAGE_ROOT }}

      - name: Cache .next/cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.PACKAGE_ROOT }}/.next/cache
          key: nextjs | $(Agent.OS) | ${{ env.PACKAGE_ROOT }}/package-lock.json

      - name: Build
        run: npm run build --workspaces=false
        working-directory: ${{ env.PACKAGE_ROOT }}

      - name: Copy Static Assets
        run: |
          cp -r .next/static .next/standalone/.next/
          cp -r public .next/standalone/
        working-directory: ${{ env.PACKAGE_ROOT }}

  build_BackendAPI:
    name: Build Backend API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet build
        run: >-
          dotnet build
          ${{ env.CI_backend_project }}

  build_Functions:
    name: Build Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ env.WEBAPP_FUNCTIONS_PACKAGE_PATH }}'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: functionsapp
          path: ${{ env.WEBAPP_FUNCTIONS_PACKAGE_PATH }}
