# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Backend API

on:
  workflow_dispatch:
    inputs:
      publish-run-id:
        description: The Workflow Run ID for a successful Publish of Monitor
        required: true
        type: string
      publish-migration-artifact:
        description: Migrations artifact name from the workflow matching the publish-run-id
        required: true
        type: string
      publish-dotnet-artifact:
        description: dotnet artifact name from the workflow matching the publish-run-id
        required: true
        type: string
  push:
    branches:
      - main
      - feat/142368/configure-pipelines

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'app/Monitor'
  DOTNET_VERSION: '8.x'
  RUN_ID: ${{ github.event.inputs.publish-run-id }}
  BUNDLE_EXECUTABLE_MIGRATION: migrate-monitor-db # CI_migration-output-filename from the publish workflow
  MIGRATION_ARTIFACT: ${{ github.event.inputs.publish-migration-artifact }}
  DOTNET_ARTIFACT: ${{ github.event.inputs.publish-dotnet-artifact }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Get Git Commit Hash
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "GIT_HASH=$calculatedSha" >> $GITHUB_ENV
      
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' -p:GitHash=${{ env.GIT_HASH }}
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # Deploy UAT
  deploy-uat-migrations:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          run_id: ${{ env.RUN_ID }}
          name: ${{ env.MIGRATION_ARTIFACT }}

      - name: Apply Migrations
        run: |
          chmod +x ${{ env.BUNDLE_EXECUTABLE_MIGRATION}}
          ./${{ env.BUNDLE_EXECUTABLE_MIGRATION }} --connection "${{ secrets.UAT_DB_CONNECTION_STRING }}"

  deploy-uat:
    needs: deploy-uat-migrations
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          run_id: ${{ env.RUN_ID }}
          name: ${{ env.MIGRATION_ARTIFACT }}
           
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_BACKEND_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_BACKEND_PUBLISH_PROFILE  }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'