# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Backend API

on:
  push:
    branches:
      - main
      - feat/142368/configure-pipelines

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'app/Monitor'
  DATABASE_MIGRATION_PATH: 'lib/*'
  DOTNET_VERSION: '8.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Get Git Commit Hash
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "GIT_HASH=$calculatedSha" >> $GITHUB_ENV
      
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' -p:GitHash=${{ env.GIT_HASH }}
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # Deploy UAT
  deploy-uat-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Apply Migrations
        run: |
          cd ${{ env.DATABASE_MIGRATION_PATH }}
          dotnet ef database update -p Data -s ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --configuration Release

  deploy-uat:
    needs: deploy-uat-migrations
    runs-on: ubuntu-latest
    needs: build
    environment: uat

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
           
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_BACKEND_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_BACKEND_PUBLISH_PROFILE  }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'